### ISSUE TITLE
Can we get website stats on downloads of assets like books and research?

### ISSUE THREAD

**Issue by claredillon** [InnerSourceCommons/InnerSourceMarketing#169]

**Comment by clcoffey** [comment]
@voborgus and @spier do you know if this is possible?

**Comment by spier** [comment]
@clcoffey I don't know where the website stats are kept. Google Analytics?
It should be possible there to search for the exact links of the books to check how often those links were accessed.

**Comment by clcoffey** [comment]
Thanks Sebastian! I'll check it out

**Comment by clcoffey** [comment]
Based on Google Analytics we had the following data from the start of 2021 until now:

State of InnerSource Report 2021 - web page: 659 page views 
State of InnerSource Report 2020 - web page: 237 page views 
State of InnerSource Report 2020 - web page:   53 page views 

Getting started with InnerSource - web page: 2557 page views
Understanding the InnerSource Checklist:       1665 page views
Managing InnerSource Projects:                          708 page views
Adopting InnerSource:                                        1850 page views
InnerSource Patterns:                                        4483 page views

I went with the links to the page rather than the link to the book because it seems like the count has been reset when we had that problem with the file downloads on the website. I can't see any downloads prior to that as the links must have changed.

**Comment by rrrutledge** [comment]
Sounds like we got what we needed out of this.
