### ISSUE TITLE
InnerSource Commons 101 for newcomers

### ISSUE THREAD

**Issue by claredillon** [InnerSourceCommons/InnerSourceMarketing#18]
Link to doc:
https://docs.google.com/document/d/1VvdgN2b0MAd7wXeNGUFaeYviguS34oBioX0XavNtbyY/edit#

## Acceptance Criteria

- [x] create a short link to doc (like [this example](https://raw.githubusercontent.com/InnerSourceCommons/innersourcecommons.org/master/pages/slackinvite.md)) => http://innersourcecommons.org/isc-101
- [x] +1 Voting for acceptance of doc
- [x] after working in the feedback, fix the version to 1.0 (also as a named version in gDrive)
- [x] publish the link to #general and pin it
- [x] add link to topic in #general

**Comment by spier** [comment]
Clare, Daniel and I had a first session about this topic and wrote up our thoughts here:
https://docs.google.com/document/d/1OlM1ZwElTc4_1HCQLsKI49WXUvj5bXiUeYiUaxr8wyg/edit#

I have promised to take our results, and turn them into tasks on the board, with specific acceptance criteria for each task.

**Comment by spier** [comment]
## Context

For the sake of this conversation, we assume:
Joining the InnerSource Commons means that a **new user is joining Slack**!
There might be other ways that users can join, but we chose to ignore them for now.

Further, this story is for newcomers to get started with contributed to the InnerSource Commons.
This is not about getting started with InnerSource as such.

## How?

When a new user joins Slack, we want to do this:

* somebody greets them in #general
* we point them to the InnerSource Commons 101 document, to help them getting started in our community

The InnerSource Commons 101 document document contains things like:

* Evolution of the InnerSource Commons
* Principles - what we are trying to do?
* Where are we now?
* How to get started?
* How to meet more people in the community (e.g. Donut)
* Where to find content that might not be public on the internet

We will produce this as a Google Doc initially, however we might opt to put this on http://innersourcecommons.org as well.

## Acceptance Criteria

* We have produced a first InnerSource Commons 101 document (as a Google Doc).
* We have shared the document with users that have joined in the last 2-3 months or so.
* We have added the doc to the #general channel, so that Newcomers can find it. (pinned / channel topic)

**Comment by spier** [comment]
I produced a first document here:
[The InnerSource Commons 101 - draft](https://docs.google.com/document/d/1VvdgN2b0MAd7wXeNGUFaeYviguS34oBioX0XavNtbyY/edit#)

Will try to get feedback from some others now.

**Comment by spier** [comment]
Before sharing this doc more widely (with newcomers), I suggest to get feedback from 
a) one member from the Patterns WG
b) one member from the Learning Path WG

Together with the Marketing WG that should cover a majority of the active users and "old timers", and with that hopefully make sure that we represent how the ISC works correctly enough :)

**Comment by lenucksi** [comment]
> Before sharing this doc more widely (with newcomers), I suggest to get feedback from
> a) one member from the Patterns WG
> b) one member from the Learning Path WG

@rrrutledge @lenucksi we should probably take a look at the document

**Comment by spier** [comment]
Make this a public gDoc.
This is assumes that it is more likely that newcomers will have gDrive access before they have github access.

**Comment by rrrutledge** [comment]
Will take a look.  Thanks!

**Comment by rrrutledge** [comment]
Reviewed and left comments in the doc.

**Comment by spier** [comment]
Great feedback. Thanks @rrrutledge.

**Comment by spier** [comment]
@mishari as you are still somewhat new to the InnerSource commons and hence have fresh eyes, could you check if anything major that a newcomer would need is missing from here? 

See: [The InnerSource Commons 101 - draft](https://docs.google.com/document/d/1VvdgN2b0MAd7wXeNGUFaeYviguS34oBioX0XavNtbyY/edit#)

**Comment by spier** [comment]
I have reached out to two more newcomers to get their feedback on the document.

**Comment by spier** [comment]
I have resolved most comments in the doc, and am waiting form some more feedback.

Will share this doc for +1 voting tomorrow, with the goal to be finished with this by Friday this week.

**Comment by lenucksi** [comment]
Also took a look, commented and looking forward to see people's reactions to it.

**Comment by spier** [comment]
All checklist tasks are complete and the ISC 101 doc is now available at http://innersourcecommons.org/isc-101

**Comment by rrrutledge** [comment]
Nice work!
