### ISSUE TITLE
Open Source Summit Europe September 19-21 (Admin)

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceMarketing#233]
- [ ] Arrange to meet with key partners
  - [ ] Glen (Analog)
  - [ ] Brian (Red Hat)
  - [ ] Wolfgang (Mercedes)
  - [ ] Guilherme (SAP)
  - [ ] Justin (GitHub)
 
- [ ] Meet with key partners
  - [ ] Glen (Analog)
  - [x] Brian (Red Hat)
  - [x] Wolfgang (Mercedes)
  - [ ] Guilherme (SAP)
  - [ ] Justin (GitHub)

**Comment by dicortazar** [comment]
I didn't see Glen or Guilherme. I was introduced to Justin one of the nights around, but didn't have the time to properly connect.

I had this conversation with Chan (Comcast) as well.

Some highlights:
* patterns or the learning path are useful tools and used internally in the companies (I'm extending this feedback from others that are not supporters or partners)
* the journey to open source is something that is of interest specifically for Red Hat (we can see the blog post by Brian a few weeks ago) and they're willing to co-create materials. This could lead to a new learning path line.
* use cases are things that people are missing and not only about the initial benefits.
* in general (again extra feedback from other people as well), people are facing an issue with InnerSource that at some point loss traction. This is either because of the benefits are not there yet or because certain lack of support. From the foundation perspective, we could help producing specific materials on convincing the leadership team, highlighting quick wins, share use cases at that journey point of time, etc.

**Comment by rrrutledge** [comment]
Thank you, Daniel!
