### ISSUE TITLE
Setup welcomer bot in the #general slack

### ISSUE THREAD

**Issue by voborgus** [InnerSourceCommons/InnerSourceMarketing#57]
Can be linked with #22. 

We need a Slack bot writing a welcome message to all #general channel newcomers with all links like to 101 document and questions needed.

**Comment by claredillon** [comment]
Noting some points from the later discussion in Slack:
- We need to make sure it is always clear that it is not necessary to share additional info on joining - only if they want to.
- We should not make over-reaching assumptions based on any answers (e.g. sometimes people's InnerSource experiences come from previous roles in a different company profile from their current role).

**Comment by lenucksi** [comment]
We could make good use of bot functions for various purposes, e.g. patterns, FAQ, ...
However, our current free Slack limits our integrations and currently we've spent all free integrations. Hence we need to either kick one out or see if there's a mcgyvered version using a user account. 

Other than that [Errbot](https://github.com/errbotio/errbot) is a popular, flexible choice for all sorts of bottery. Same is Hubot, however that one is pure JS.

**Comment by spier** [comment]
I like the idea of a bot doing repetitive work for us that we would otherwise forget.

I would keep these two activities separate though:

1. newcomer joins slack, and is greeted by the bot with a pointer to http://innersourcecommons.org/isc-101 and some questions as outlined in [this Slack thread](https://innersourcecommons.slack.com/archives/CUWFGQJ8K/p1597911909000500)
1. once the newcomer is in Slack for some time (say 1-2 months), the bot asks them a couple of questions about their ISC onboarding experience (as outlined in #22)

On a fixed cadence we can then review what we learned about the onboarding experience of newcomers, and adapt as we see fit.

**Comment by voborgus** [comment]
Done here

**Comment by spier** [comment]
Closing this issue, to make it even more clear that it is done :)
(will also double check why this didn't happen automatically when moving the card)

**Comment by rrrutledge** [comment]
How can I see and interact with this bit to see what the experience is like for a newcomer?
