### ISSUE TITLE
Social following and share

### ISSUE THREAD

**Issue by clcoffey** [InnerSourceCommons/InnerSourceMarketing#81]
### Purpose & Details

By following us on social channels and sharing our content you will help us spread the word about InnerSource, grow our channels and reach more audiences. 

### Acceptance Criteria

- Follow InnerSource Commons on social media.
- Follow on Twitter: [@InnerSourceOrg](http://twitter.com/InnerSourceOrg)
- Follow on LinkedIn: [InnerSource Commons Foundation](https://linkedin.com/company/innersourcecommons)
- Subscribe on Youtube: [InnerSource Commons](https://www.youtube.com/channel/UCoSPSd6Or4F_vpjo4SmyoEA)
- Share our latest posts
- Once you have done so, please:
        - Close this issue
        - Open a new issue based on the template "Social following and share"
        - Before saving make sure to add the issue to the Marketing WG Board in the Project section on the right. Once you have done this, you will see a dropdown box under the green bar within the Project: "Awaiting triage".
        - Please change "Awaiting Triage" to "To Do"

This will allow us to keep track of and acknowledge your contribution and it will give the chance to the next person that is interested in contributing to pick up this issue.

**Comment by spier** [comment]
@clcoffey just FYI, the GitHub Action that we use for this automation also has an option now to pin this issue whenever it gets recreated. Pinning the issue makes it easier for new contributors to spot the issue (as pinned issues are shown above all other issues at the very top of the issue list).

I have just pinned this issue, so that you can check here how it looks like:
https://github.com/InnerSourceCommons/InnerSourceMarketing/issues

Let me know if you want to use that automatic pinning feature, and I can adapt the workflow.

**Comment by clcoffey** [comment]
That looks great Sebastian! If it's not too much work it would be great to have it. If not we can just do it manually as it doesn't seem like we get a lot of action on it at the moment

**Comment by spier** [comment]
It's a tiny change. I will use this PR to add the pinning feature:
https://github.com/InnerSourceCommons/InnerSourceMarketing/pull/113

**Comment by spier** [comment]
Testing that the issue re-creation works.

**Comment by spier** [comment]
@clcoffey the automatic pinning of the newly created "Social following and share" is working now.
See #116 which was created and pinned automatically this way.

**Comment by clcoffey** [comment]
Thanks Sebastian! Yopu're a star! :-)
