### ISSUE TITLE
Update website Events page to include past and upcoming events

### ISSUE THREAD

**Issue by clcoffey** [InnerSourceCommons/InnerSourceMarketing#98]
Please update the website Events page to differentiate between Past Events and Upcoming Events.

Considering that we now have multiple Upcoming events (2 monthly Community Calls and Summit) it would be great for the Events page to show these events in two different sections:
- Upcoming Events
- Past events

**Comment by voborgus** [comment]
thanks for this, @clcoffey!

Because of the rare events held by ISC usually (three events in one time it's a happy exception), will be sad to have a sign "No events in future :(" in the silent periods.

IMHO it's better to not have this separation, but have:

* Ability to have multiple notices per page (including ones appearing in every page). Like:
![image](https://user-images.githubusercontent.com/9394918/129242650-518257a7-4f36-44d9-b271-1101b48a3768.png)

* Have no featured event to spread attention to all items in the list:

![image](https://user-images.githubusercontent.com/9394918/129245082-aec85963-2fff-47d6-a47d-df39950f1ddc.png)

Will this suit our needs?

**Comment by claredillon** [comment]
My concern is that there is no indication on many of our events as to when they are/were... so as you can see from the following screenshot, you may think Guilherme & Michael's event is still open. Even with the other two (where we included the date on the image), the overview is written in the present tense, so it looks like they are still current. 

When we have more than one in the future - it will be even harder, as there will still only be one first, and then a mix of future and past. 

There are two ways I can think of to make this unambiguous:
1. Put in a "Past Events" title. I have no problem with a "no planned events at this time" notice, if we have no planned events. Better to be honest than confuse people/ disappoint them if they try to register for an old event. Also, with the planned community call schedule now unfolding, I don't see that being an issue like it was in the past.
2. Put "Register Now" as the action/button for the current ones and something like "learn more" for the older ones. 

![image](https://user-images.githubusercontent.com/32961070/129362385-60bb8443-4908-4e60-a78c-ebc9f5cdad17.png)

**Comment by voborgus** [comment]
Will look what we can do here, thanks!

**Comment by voborgus** [comment]
With [this PR](https://github.com/InnerSourceCommons/innersourcecommons.org/pull/149), the new appearance looks like:

![image](https://user-images.githubusercontent.com/9394918/130410626-ac96880a-dfd8-4b3a-9810-5812eb973ff2.png)

Changes made:

* **Removed `featured: true` functionality**. The new logic: all future events are big and located at the top, rest are small and going after the "Past Events" title.
* Used `publish date` [parameter in the page](https://github.com/InnerSourceCommons/innersourcecommons.org/pull/149/files#diff-d7f2bb93d6d4f463147359b4064a0eab8e0f54d2c0eecc77895a39ef5bcfb739R7) to ensure the page is visible and the event date is correct.
* Buttons are "Register Now" for future events and "Open Event" for the past.

Waiting for your approval on the PR and happy to merge.

FYI @clcoffey  @claredillon

**Comment by voborgus** [comment]
BTW, how to put the big warning sign "CFP is Open" to all pages:

Insert the code like

```
<section class="notice bg-primary text-light">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-md-12 text-center">
        <a class="text-light" href="http://innersourcecommons.org">Call For Papers</a> is open for InnerSource Commons Summit 2021. Save the dates – 17th November, 2021
      </div>
    </div>
  </div>
</section>
```
To the very end of [header.html](https://github.com/InnerSourceCommons/innersourcecommons.org/blob/master/layouts/partials/header.html)

There are no open PRs currently with that since there is no public information about the CFP opening.

**Comment by voborgus** [comment]
Live on the site: https://innersourcecommons.org/events/
